<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Name | Senior Data Engineer</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        :root {
            --primary: #2563eb;
            --secondary: #1e40af;
            --dark: #1e293b;
            --light: #f8fafc;
            --accent: #3b82f6;
            --text: #334155;
            --border: #e2e8f0;
        }

        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: var(--text);
            background: var(--light);
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 20px;
        }

        header {
            background: linear-gradient(135deg, var(--primary) 0%, var(--secondary) 100%);
            color: white;
            padding: 80px 0;
            text-align: center;
        }

        header h1 {
            font-size: 3rem;
            margin-bottom: 10px;
            font-weight: 700;
        }

        header p {
            font-size: 1.3rem;
            opacity: 0.95;
            margin-bottom: 30px;
        }

        .social-links {
            display: flex;
            gap: 20px;
            justify-content: center;
            margin-top: 20px;
        }

        .social-links a {
            color: white;
            text-decoration: none;
            padding: 10px 20px;
            border: 2px solid white;
            border-radius: 5px;
            transition: all 0.3s;
            font-weight: 500;
        }

        .social-links a:hover {
            background: white;
            color: var(--primary);
            transform: translateY(-2px);
        }

        nav {
            background: white;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            position: sticky;
            top: 0;
            z-index: 100;
        }

        nav ul {
            display: flex;
            justify-content: center;
            list-style: none;
            padding: 20px 0;
            flex-wrap: wrap;
        }

        nav li {
            margin: 0 20px;
        }

        nav a {
            color: var(--text);
            text-decoration: none;
            font-weight: 600;
            transition: color 0.3s;
            padding: 5px 0;
            border-bottom: 2px solid transparent;
        }

        nav a:hover {
            color: var(--primary);
            border-bottom-color: var(--primary);
        }

        section {
            padding: 80px 0;
        }

        section h2 {
            font-size: 2.5rem;
            color: var(--dark);
            margin-bottom: 40px;
            text-align: center;
            position: relative;
        }

        section h2::after {
            content: '';
            position: absolute;
            bottom: -10px;
            left: 50%;
            transform: translateX(-50%);
            width: 60px;
            height: 4px;
            background: var(--primary);
            border-radius: 2px;
        }

        .about-content {
            background: white;
            padding: 40px;
            border-radius: 10px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.08);
            max-width: 900px;
            margin: 0 auto;
        }

        .about-content p {
            font-size: 1.1rem;
            margin-bottom: 20px;
            line-height: 1.8;
        }

        .skills-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
            gap: 30px;
            margin-top: 40px;
        }

        .skill-category {
            background: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.08);
            transition: transform 0.3s, box-shadow 0.3s;
        }

        .skill-category:hover {
            transform: translateY(-5px);
            box-shadow: 0 8px 30px rgba(0,0,0,0.12);
        }

        .skill-category h3 {
            color: var(--primary);
            font-size: 1.4rem;
            margin-bottom: 20px;
            display: flex;
            align-items: center;
            gap: 10px;
        }

        .skill-category ul {
            list-style: none;
        }

        .skill-category li {
            padding: 8px 0;
            color: var(--text);
            font-size: 0.95rem;
            border-bottom: 1px solid var(--border);
        }

        .skill-category li:last-child {
            border-bottom: none;
        }

        .projects-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
            gap: 30px;
            margin-top: 40px;
        }

        .project-card {
            background: white;
            border-radius: 10px;
            overflow: hidden;
            box-shadow: 0 4px 20px rgba(0,0,0,0.08);
            transition: transform 0.3s, box-shadow 0.3s;
        }

        .project-card:hover {
            transform: translateY(-5px);
            box-shadow: 0 8px 30px rgba(0,0,0,0.12);
        }

        .project-header {
            background: linear-gradient(135deg, var(--primary) 0%, var(--secondary) 100%);
            color: white;
            padding: 30px;
        }

        .project-header h3 {
            font-size: 1.5rem;
            margin-bottom: 10px;
        }

        .project-body {
            padding: 30px;
        }

        .project-body p {
            margin-bottom: 20px;
            color: var(--text);
        }

        .tech-tags {
            display: flex;
            flex-wrap: wrap;
            gap: 10px;
            margin-top: 20px;
        }

        .tech-tag {
            background: var(--light);
            color: var(--primary);
            padding: 5px 15px;
            border-radius: 20px;
            font-size: 0.85rem;
            font-weight: 600;
            border: 1px solid var(--border);
        }

        .contact-content {
            background: white;
            padding: 50px;
            border-radius: 10px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.08);
            max-width: 600px;
            margin: 0 auto;
            text-align: center;
        }

        .contact-content p {
            font-size: 1.2rem;
            margin-bottom: 30px;
        }

        .contact-links {
            display: flex;
            flex-direction: column;
            gap: 15px;
            align-items: center;
        }

        .contact-links a {
            color: var(--primary);
            text-decoration: none;
            font-size: 1.1rem;
            font-weight: 600;
            transition: color 0.3s;
        }

        .contact-links a:hover {
            color: var(--secondary);
        }

        footer {
            background: var(--dark);
            color: white;
            text-align: center;
            padding: 30px 0;
            margin-top: 80px;
        }

        @media (max-width: 768px) {
            header h1 {
                font-size: 2rem;
            }

            header p {
                font-size: 1.1rem;
            }

            section h2 {
                font-size: 2rem;
            }

            .skills-grid,
            .projects-grid {
                grid-template-columns: 1fr;
            }

            nav ul {
                flex-direction: column;
                align-items: center;
            }

            nav li {
                margin: 10px 0;
            }
        }
    </style>
</head>
<body>
    <header>
        <div class="container">
            <h1>Your Name</h1>
            <p>Senior Data Engineer | Building Scalable Data Solutions</p>
            <div class="social-links">
                <a href="https://github.com/yourusername" target="_blank">GitHub</a>
                <a href="https://linkedin.com/in/yourprofile" target="_blank">LinkedIn</a>
                <a href="mailto:your.email@example.com">Email</a>
            </div>
        </div>
    </header>

    <nav>
        <ul>
            <li><a href="#about">About</a></li>
            <li><a href="#skills">Skills</a></li>
            <li><a href="#projects">Projects</a></li>
            <li><a href="#contact">Contact</a></li>
        </ul>
    </nav>

    <section id="about">
        <div class="container">
            <h2>About Me</h2>
            <div class="about-content">
                <p>
                    I'm a Senior Data Engineer with over X years of experience designing and implementing 
                    robust data pipelines, architecting data warehouses, and enabling data-driven decision 
                    making at scale.
                </p>
                <p>
                    My expertise lies in building scalable data infrastructure that processes millions of 
                    events daily, optimizing query performance, and establishing data quality frameworks. 
                    I'm passionate about turning complex data challenges into elegant, performant solutions.
                </p>
                <p>
                    When I'm not engineering data solutions, you can find me exploring new technologies, 
                    contributing to open-source projects, or mentoring aspiring data engineers.
                </p>
            </div>
        </div>
    </section>

    <section id="skills">
        <div class="container">
            <h2>Technical Skills</h2>
            <div class="skills-grid">
                <div class="skill-category">
                    <h3>🐍 Languages</h3>
                    <ul>
                        <li>Python</li>
                        <li>SQL</li>
                        <li>Scala</li>
                        <li>Java</li>
                        <li>Bash/Shell</li>
                    </ul>
                </div>

                <div class="skill-category">
                    <h3>☁️ Cloud Platforms</h3>
                    <ul>
                        <li>AWS (S3, Redshift, EMR, Glue)</li>
                        <li>GCP (BigQuery, Dataflow)</li>
                        <li>Azure (Synapse, Data Factory)</li>
                        <li>Databricks</li>
                    </ul>
                </div>

                <div class="skill-category">
                    <h3>⚡ Big Data Tools</h3>
                    <ul>
                        <li>Apache Spark</li>
                        <li>Apache Kafka</li>
                        <li>Apache Airflow</li>
                        <li>dbt</li>
                        <li>Apache Flink</li>
                    </ul>
                </div>

                <div class="skill-category">
                    <h3>🗄️ Databases</h3>
                    <ul>
                        <li>Snowflake</li>
                        <li>PostgreSQL</li>
                        <li>MongoDB</li>
                        <li>Cassandra</li>
                        <li>Redis</li>
                    </ul>
                </div>

                <div class="skill-category">
                    <h3>🛠️ DevOps & Tools</h3>
                    <ul>
                        <li>Docker</li>
                        <li>Kubernetes</li>
                        <li>Terraform</li>
                        <li>GitHub Actions</li>
                        <li>Jenkins</li>
                    </ul>
                </div>

                <div class="skill-category">
                    <h3>📊 Data Quality</h3>
                    <ul>
                        <li>Great Expectations</li>
                        <li>dbt tests</li>
                        <li>Data lineage tracking</li>
                        <li>Metadata management</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <section id="projects">
        <div class="container">
            <h2>Featured Projects</h2>
            <div class="projects-grid">
                <div class="project-card">
                    <div class="project-header">
                        <h3>Real-Time Analytics Pipeline</h3>
                    </div>
                    <div class="project-body">
                        <p>
                            Built a real-time data pipeline processing 10M+ events daily using Kafka and Spark 
                            Streaming, reducing data latency from hours to seconds.
                        </p>
                        <div class="tech-tags">
                            <span class="tech-tag">Kafka</span>
                            <span class="tech-tag">Spark</span>
                            <span class="tech-tag">AWS</span>
                            <span class="tech-tag">Python</span>
                        </div>
                    </div>
                </div>

                <div class="project-card">
                    <div class="project-header">
                        <h3>Data Warehouse Modernization</h3>
                    </div>
                    <div class="project-body">
                        <p>
                            Migrated legacy data warehouse to Snowflake, implementing dbt for transformations 
                            and reducing query times by 60%.
                        </p>
                        <div class="tech-tags">
                            <span class="tech-tag">Snowflake</span>
                            <span class="tech-tag">dbt</span>
                            <span class="tech-tag">SQL</span>
                            <span class="tech-tag">Airflow</span>
                        </div>
                    </div>
                </div>

                <div class="project-card">
                    <div class="project-header">
                        <h3>ML Feature Pipeline</h3>
                    </div>
                    <div class="project-body">
                        <p>
                            Designed and implemented a feature engineering pipeline for ML models, serving 
                            features to 20+ data science teams.
                        </p>
                        <div class="tech-tags">
                            <span class="tech-tag">PySpark</span>
                            <span class="tech-tag">GCP</span>
                            <span class="tech-tag">BigQuery</span>
                            <span class="tech-tag">Kubernetes</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="contact">
        <div class="container">
            <h2>Get In Touch</h2>
            <div class="contact-content">
                <p>
                    I'm always interested in hearing about new opportunities, collaborations, 
                    or just connecting with fellow data enthusiasts!
                </p>
                <div class="contact-links">
                    <a href="mailto:your.email@example.com">✉️ your.email@example.com</a>
                    <a href="https://linkedin.com/in/yourprofile" target="_blank">💼 LinkedIn Profile</a>
                    <a href="https://github.com/yourusername" target="_blank">🐙 GitHub Profile</a>
                </div>
            </div>
        </div>
    </section>

    <footer>
        <div class="container">
            <p>&copy; 2025 Your Name. All rights reserved.</p>
        </div>
    </footer>
</body>
</html>